name: test-cygwin

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    env:
      CHERE_INVOKING: 1
      TMP: "/tmp"
      TEMP: "/tmp"
    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --noprofile --norc -exo pipefail -o igncr "{0}"

    steps:
    - name: Force LF line endings
      run: |
        git config --global core.autocrlf false  # Affects the non-Cygwin git.
      shell: bash

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - uses: cygwin/cygwin-install-action@v4
      with:
        packages: python39 python39-pip python39-virtualenv git

    - name: Limit $PATH to Cygwin
      run: |
        echo 'C:\cygwin\bin' > "$GITHUB_PATH"  # Overwrite it with just this.

    - name: Special configuration for Cygwin's git
      run: |
        git config --global --add safe.directory "$(pwd)"
        git config --global core.autocrlf false

    - name: Prepare this repo for tests
      run: |
        TRAVIS=yes ./init-tests-after-clone.sh

    - name: Further prepare git configuration for tests
      run: |
        git config --global user.email "travis@ci.com"
        git config --global user.name "Travis Runner"
        # If we rewrite the user's config by accident, we will mess it up
        # and cause subsequent tests to fail
        cat test/fixtures/.gitconfig >> ~/.gitconfig

    - name: Update PyPA packages
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install project and test dependencies
      run: |
        python -m pip install ".[test]"

    - name: Show version and platform information
      run: |
        uname -a
        command -v git python
        git version
        python --version
        python -c 'import sys; print(sys.platform)'
        python -c 'import os; print(os.name)'
        python -c 'import git; print(git.compat.is_win)'

    - name: Test with pytest
      run: |
        python -m pytest --color=yes -p no:sugar --instafail -vv
